services:

  postgres:
    image: postgres:16
    container_name: commerce-postgres
    restart: always

    environment:
      POSTGRES_DB: commerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5438:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: